version: "3.3"
services:
  kafka-broker:
    image: confluentinc/cp-kafka:5.5.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka-broker
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG4J_ROOT_LOGLEVEL=ERROR
      - KAFKA_LOG4J_LOGGERS=org.apache.zookeeper=ERROR,org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.2
    container_name: kafka-zookeeper
    expose:
      - "2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    depends_on:
      - zookeeper
      - kafka-broker
    ports:
      - "8091:8091"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8091
    extra_hosts:
      - "localhost:127.0.0.1"
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_USER: test-user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  api:
    image: image #FIXME your image here
    environment:
      RDS_HOSTNAME: mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql
#--env MYSQL_ROOT_PASSWORD=dummypassword --env MYSQL_USER=todos-user
#  --env MYSQL_PASSWORD=dummytodos --env MYSQL_DATABASE=todos
#  --name mysql --publish 3306:3306 mysql:5.7
